Repository hyundai-shallwescan/client, pull requests merged in 2024-09, with the labels that each got.

#4 [SWS-75] 장바구니 아이템 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ite/sws/domain/cart/api/repository/ScanRepository.kt
  app/src/main/java/com/ite/sws/domain/cart/api/service/ScanService.kt
  app/src/main/java/com/ite/sws/domain/cart/data/PutCartItemReq.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ScanFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ScanViewModel.kt
  app/src/main/java/com/ite/sws/util/ShowCustomDialog.kt
  app/src/main/res/drawable/bg_dialog.xml
  app/src/main/res/drawable/bg_scanner.xml
  app/src/main/res/drawable/btn_large_green.xml
  app/src/main/res/drawable/btn_small_gray.xml
  app/src/main/res/drawable/btn_small_green.xml
  app/src/main/res/layout/dialog_title_message_twobtn.xml
  app/src/main/res/layout/dialog_title_onebtn.xml
  app/src/main/res/layout/dialog_title_twobtn.xml
  app/src/main/res/layout/fragment_scan.xml
  app/src/main/res/layout/layout_barcode_scanner.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles: enhancement

#5 [SWS-77] 마이페이지 UI 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ite/sws/MainActivity.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/ExampleFragment.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/MyPurchaseHistoryActivity.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/MyReviewActivity.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/MypageFragment.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/UpdateProfileActivity.kt
  app/src/main/res/drawable/btn_circle.png
  app/src/main/res/drawable/btn_light_green.xml
  app/src/main/res/drawable/btn_white_shadow.png
  app/src/main/res/drawable/ic_pencil.xml
  app/src/main/res/drawable/img_pancake_heendy.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_my_purchase_history.xml
  app/src/main/res/layout/activity_my_review.xml
  app/src/main/res/layout/activity_update_profile.xml
  app/src/main/res/layout/fragment_example.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: :sparkles: enhancement

#6 [SWS-73] 장바구니 로그인
  app/src/androidTest/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ite/sws/MainActivity.kt
  app/src/main/java/com/ite/sws/common/WebSocketClient.kt
  app/src/main/java/com/ite/sws/domain/cart/api/repository/CartRepository.kt
  app/src/main/java/com/ite/sws/domain/cart/api/service/CartService.kt
  app/src/main/java/com/ite/sws/domain/cart/data/PostCartLoginReq.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/CartLoginFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ScanFragment.kt
  app/src/main/java/com/ite/sws/domain/chat/data/ChatMessageDTO.kt
  app/src/main/java/com/ite/sws/domain/chat/view/ui/ChatFragment.kt
  app/src/main/java/com/ite/sws/util/SharedPreferencesUtil.kt
  app/src/main/java/com/ite/sws/util/replaceFragmentWithAnimation.kt
  app/src/main/res/drawable/bg_login.png
  app/src/main/res/drawable/rounded_login_box.xml
  app/src/main/res/drawable/rounded_main_btn.xml
  app/src/main/res/drawable/rounded_top_left.xml
  app/src/main/res/layout/fragment_cart_login.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_scan.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles: enhancement

#7 [SWS-101] 내비게이션 숨김처리 및 툴바 타이틀 설정 함수 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ite/sws/MainActivity.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/MyPurchaseHistoryActivity.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/MyReviewActivity.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/MyReviewFragment.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/MypageFragment.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/UpdateProfileActivity.kt
  app/src/main/java/com/ite/sws/util/HideBottomNavigation.kt
  app/src/main/java/com/ite/sws/util/SetupToolbar.kt
  app/src/main/res/drawable/ic_arrow_top.xml
  app/src/main/res/layout/activity_my_purchase_history.xml
  app/src/main/res/layout/activity_my_review.xml
  app/src/main/res/layout/fragment_my_review.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/toolbar.xml
  app/src/main/res/layout/toolbar_with_back.xml
  app/src/main/res/values/themes.xml
Labels: :sparkles: enhancement

#8 [SWS-75] 커스텀 다이얼로그 호출 시, 의도하지 않은 움직임 수정
  app/build.gradle
  app/src/main/java/com/ite/sws/MainActivity.kt
  app/src/main/java/com/ite/sws/domain/cart/api/repository/ScanRepository.kt
  app/src/main/java/com/ite/sws/domain/cart/api/service/ScanService.kt
  app/src/main/java/com/ite/sws/domain/cart/data/CartItem.kt
  app/src/main/java/com/ite/sws/domain/cart/data/GetCartItemRes.kt
  app/src/main/java/com/ite/sws/domain/cart/view/adapter/CartRecyclerAdapter.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ContainerFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ScanFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ScanViewModel.kt
  app/src/main/java/com/ite/sws/domain/sharelist/view/ui/ShareListFragment.kt
  app/src/main/java/com/ite/sws/util/CustomDialog.kt
  app/src/main/java/com/ite/sws/util/ShowCustomDialog.kt
  app/src/main/res/drawable/bg_cart.xml
  app/src/main/res/drawable/bg_list_item.xml
  app/src/main/res/drawable/bg_list_item_img.xml
  app/src/main/res/drawable/bg_round_line_green.xml
  app/src/main/res/drawable/bg_round_white.xml
  app/src/main/res/drawable/bg_segmented_control.xml
  app/src/main/res/drawable/bg_slider.xml
  app/src/main/res/drawable/btn_scan_additional.xml
  app/src/main/res/drawable/ic_arrow_right_green.xml
  app/src/main/res/drawable/ic_cart.xml
  app/src/main/res/drawable/ic_minus.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_scan_additional.xml
  app/src/main/res/drawable/ic_scan_chat.xml
  app/src/main/res/drawable/img_product.png
  app/src/main/res/layout/dialog_text1_btn1.xml
  app/src/main/res/layout/dialog_text1_btn2.xml
  app/src/main/res/layout/dialog_text2_btn2.xml
  app/src/main/res/layout/fragment_container.xml
  app/src/main/res/layout/fragment_scan.xml
  app/src/main/res/layout/fragment_share_list.xml
  app/src/main/res/layout/item_cart.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/strings.xml
  gradle.properties
Labels: :sparkles: enhancement

#11 [SWS-103] 장바구니 아이템 조회 API 연동
  app/src/main/java/com/ite/sws/domain/cart/view/adapter/CartRecyclerAdapter.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ExternalCartFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ExternalCartViewModel.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ExternalContainerFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ScanFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ScanViewModel.kt
  app/src/main/res/drawable/img_wink_heendy.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_external_share_list.xml
  app/src/main/res/layout/fragment_scan.xml
  app/src/main/res/layout/item_cart.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles: enhancement

#12 [SWS-106] 로그인 UI 수정 및 레트로핏 인터셉터 설정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ite/sws/MainActivity.kt
  app/src/main/java/com/ite/sws/MainApplication.kt
  app/src/main/java/com/ite/sws/common/RetrofitClient.kt
  app/src/main/java/com/ite/sws/domain/member/api/repository/MemberRepository.kt
  app/src/main/java/com/ite/sws/domain/member/api/service/MemberService.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/LoginFragment.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/MypageFragment.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/SignUpFragment.kt
  app/src/main/java/com/ite/sws/util/SharedPreferencesUtil.kt
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_my_review.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: :sparkles: enhancement

#13 [SWS-108] 로그아웃
  app/src/main/java/com/ite/sws/domain/member/api/repository/MemberRepository.kt
  app/src/main/java/com/ite/sws/domain/member/api/service/MemberService.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/LoginFragment.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/MypageFragment.kt
  app/src/main/java/com/ite/sws/util/SharedPreferencesUtil.kt
Labels: :sparkles: enhancement

#14 [SWS-95] 채팅 API 연동
  app/src/main/java/com/ite/sws/common/WebSocketClient.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/CartLoginFragment.kt
  app/src/main/java/com/ite/sws/domain/chat/data/ChatMessageDTO.kt
  app/src/main/java/com/ite/sws/domain/chat/view/ui/ChatFragment.kt
Labels: :sparkles: enhancement

#15 [SWS-105] 장바구니 아이템 수정 및 삭제
  app/build.gradle
  app/src/main/java/com/ite/sws/domain/cart/api/repository/CartRepository.kt
  app/src/main/java/com/ite/sws/domain/cart/api/service/CartService.kt
  app/src/main/java/com/ite/sws/domain/cart/data/CartItem.kt
  app/src/main/java/com/ite/sws/domain/cart/data/GetCartItemRes.kt
  app/src/main/java/com/ite/sws/domain/cart/view/adapter/CartRecyclerAdapter.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ScanFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ScanViewModel.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ScanViewModelFactory.kt
  app/src/main/java/com/ite/sws/util/SwipeHelperCallback.kt
  app/src/main/res/drawable/bg_trash.xml
  app/src/main/res/layout/item_cart.xml
Labels: :sparkles: enhancement

#16 [SWS-89] 회원 탈퇴
  app/src/main/java/com/ite/sws/domain/member/api/repository/MemberRepository.kt
  app/src/main/java/com/ite/sws/domain/member/api/service/MemberService.kt
  app/src/main/java/com/ite/sws/domain/member/data/PostLoginRes.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/LoginFragment.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/MypageFragment.kt
  app/src/main/java/com/ite/sws/util/SharedPreferencesUtil.kt
  app/src/main/res/layout/fragment_my_review.xml
Labels: :sparkles: enhancement

#17 [SWS-111] 비회원 로그인 화면 처리 적용
  app/src/main/java/com/ite/sws/MainActivity.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/CartLoginFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ExternalContainerFragment.kt
  app/src/main/java/com/ite/sws/domain/chat/view/ui/ChatFragment.kt
  app/src/main/java/com/ite/sws/util/SharedPreferencesUtil.kt
Labels: :sparkles: enhancement

#19 [SWS-82] 회원가입 UI 및 API 연동
  app/src/main/java/com/ite/sws/domain/member/api/repository/MemberRepository.kt
  app/src/main/java/com/ite/sws/domain/member/api/service/MemberService.kt
  app/src/main/java/com/ite/sws/domain/member/data/PostMemberReq.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/LoginFragment.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/MyReviewFragment.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/MypageFragment.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/SignUpFragment.kt
  app/src/main/res/drawable/btn_small_white_shadow.png
  app/src/main/res/drawable/btn_xsmall_white_shadow.png
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles: enhancement

#20 [SWS-112] fadein, fadeout 커스텀 애니메이션 생성
  app/src/main/java/com/ite/sws/util/ReplaceFragmentWithAnimation.kt
  app/src/main/res/anim/anim_fade_in.xml
  app/src/main/res/anim/anim_fade_out.xml
Labels: :sparkles: enhancement

#22 [SWS-90] 웹소켓 연결로 실시간으로 장바구니 아이템 변경 사항 반영
  app/src/main/java/com/ite/sws/domain/cart/api/repository/CartRepository.kt
  app/src/main/java/com/ite/sws/domain/cart/data/CartItemDetail.kt
  app/src/main/java/com/ite/sws/domain/cart/view/adapter/BaseCartAdapter.kt
  app/src/main/java/com/ite/sws/domain/cart/view/adapter/CartRecyclerAdapter.kt
  app/src/main/java/com/ite/sws/domain/cart/view/adapter/ExternalCartRecyclerAdapter.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ContainerFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ExternalCartFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ExternalContainerFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ScanFragment.kt
  app/src/main/java/com/ite/sws/util/NumberFormatterUtil.kt
  app/src/main/java/com/ite/sws/util/SwipeHelperCallback.kt
Labels: :sparkles: enhancement

#24 [SWS-85] 리뷰 관리 UI 구현
  app/src/main/java/com/ite/sws/domain/member/data/GetMemberPaymentRes.kt
  app/src/main/java/com/ite/sws/domain/member/data/GetMemberReviewRes.kt
  app/src/main/java/com/ite/sws/domain/member/view/adapter/MyReviewRecyclerViewAdapter.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/MyReviewFragment.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/WrittenReviewFragment.kt
  app/src/main/java/com/ite/sws/domain/review/view/ui/WriteReviewFragment.kt
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/layout/fragment_my_review.xml
  app/src/main/res/layout/fragment_my_review_written.xml
  app/src/main/res/layout/fragment_write_review.xml
  app/src/main/res/layout/item_review.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles: enhancement

#25 [SWS-96] 채팅 UI
  app/src/main/java/com/ite/sws/MainActivity.kt
  app/src/main/java/com/ite/sws/domain/chat/api/repository/ChatRepository.kt
  app/src/main/java/com/ite/sws/domain/chat/api/service/ChatService.kt
  app/src/main/java/com/ite/sws/domain/chat/view/adapter/ChatAdapter.kt
  app/src/main/java/com/ite/sws/domain/chat/view/ui/ChatFragment.kt
  app/src/main/res/drawable/btn_chat_send.xml
  app/src/main/res/drawable/ic_chat_divider.png
  app/src/main/res/drawable/ic_chat_recieved.9.png
  app/src/main/res/drawable/ic_chat_sent.9.png
  app/src/main/res/drawable/img_chat_wink_heendy.png
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/item_chat_received.xml
  app/src/main/res/layout/item_chat_sent.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles: enhancement

#26 [SWS-116] 작성 리뷰 조회 API 연동
  app/build.gradle
  app/src/main/java/com/ite/sws/domain/member/api/repository/MemberRepository.kt
  app/src/main/java/com/ite/sws/domain/member/api/repository/ReviewPagingSource.kt
  app/src/main/java/com/ite/sws/domain/member/api/service/MemberService.kt
  app/src/main/java/com/ite/sws/domain/member/view/adapter/MyReviewRecyclerViewAdapter.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/MemberViewModel.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/MyPaymentFragment.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/WrittenReviewFragment.kt
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/layout/item_review.xml
Labels: :sparkles: enhancement

#27 [SWS-93] 체크리스트 조회 및 체크 상태 변경
  app/src/main/java/com/ite/sws/common/data/CheckStatus.kt
  app/src/main/java/com/ite/sws/domain/checklist/api/repository/CheckListRepository.kt
  app/src/main/java/com/ite/sws/domain/checklist/api/service/CheckListService.kt
  app/src/main/java/com/ite/sws/domain/checklist/data/CheckListCategory.kt
  app/src/main/java/com/ite/sws/domain/checklist/data/GetCheckListRes.kt
  app/src/main/java/com/ite/sws/domain/checklist/view/adapter/CheckListRecyclerViewAdapter.kt
  app/src/main/java/com/ite/sws/domain/checklist/view/ui/CheckListFragment.kt
  app/src/main/java/com/ite/sws/domain/checklist/view/ui/CheckListViewModel.kt
  app/src/main/java/com/ite/sws/domain/checklist/view/ui/ChecklistFragment.kt
  app/src/main/java/com/ite/sws/domain/member/api/repository/MemberRepository.kt
  app/src/main/java/com/ite/sws/domain/member/view/adapter/MyPaymentItemRecyclerViewAdapter.kt
  app/src/main/java/com/ite/sws/domain/member/view/adapter/MyPaymentRecyclerViewAdapter.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/ModifyMemberFragment.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/MypageFragment.kt
  app/src/main/res/drawable/bg_checklist.png
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_checked.xml
  app/src/main/res/drawable/ic_fruit.xml
  app/src/main/res/drawable/ic_unchecked.xml
  app/src/main/res/drawable/selector_check_status.xml
  app/src/main/res/layout/fragment_checklist.xml
  app/src/main/res/layout/item_checklist.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles: enhancement

#28 [SWS-124] 회원 구매 내역 상품 ID 필드 추가
  app/src/main/java/com/ite/sws/domain/member/data/GetMemberPaymentRes.kt
Labels: :sparkles: enhancement

#30 [SWS-118] 장바구니 아이템 등록 시, 첫 아이템일 시 리사이클러뷰가 안 보이는 문제 해결
  app/src/main/java/com/ite/sws/domain/cart/view/adapter/BaseCartAdapter.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/BaseCartViewModel.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ExternalCartViewModel.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ScanFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ScanViewModel.kt
Labels: :bug: bug

#29 [SWS-100] 주차시간조회-UI-및-API연동
  app/src/main/java/com/ite/sws/domain/parking/api/repository/ParkingRepository.kt
  app/src/main/java/com/ite/sws/domain/parking/api/service/ParkingService.kt
  app/src/main/java/com/ite/sws/domain/parking/data/GetParkingRes.kt
  app/src/main/java/com/ite/sws/domain/parking/view/ui/ParkingFragment.kt
  app/src/main/res/drawable/btn_rounded_light_green.xml
  app/src/main/res/drawable/ic_parking_car.xml
  app/src/main/res/drawable/ic_parking_free.xml
  app/src/main/res/layout/fragment_parking.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles: enhancement

#33 [SWS-125] 상품결제 UI
  app/src/main/java/com/ite/sws/domain/cart/api/repository/CartRepository.kt
  app/src/main/java/com/ite/sws/domain/cart/api/service/CartService.kt
  app/src/main/java/com/ite/sws/domain/cart/view/adapter/BaseCartAdapter.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ContainerFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/CustomBottomSheetFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ExternalContainerFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ScanFragment.kt
  app/src/main/java/com/ite/sws/domain/payment/api/repository/PaymentRepository.kt
  app/src/main/java/com/ite/sws/domain/payment/api/service/PaymentService.kt
  app/src/main/java/com/ite/sws/domain/payment/view/adapter/PaymentRecyclerAdapter.kt
  app/src/main/java/com/ite/sws/domain/payment/view/ui/PaymentFragment.kt
  app/src/main/java/com/ite/sws/domain/payment/view/ui/PaymentViewModel.kt
  app/src/main/java/com/ite/sws/util/ClipBoardUtil.kt
  app/src/main/res/drawable/bg_rounded_top.xml
  app/src/main/res/drawable/bg_spinner_down.xml
  app/src/main/res/drawable/btn_kakao.png
  app/src/main/res/drawable/btn_link.png
  app/src/main/res/drawable/btn_rounded_14_main.xml
  app/src/main/res/drawable/btn_rounded_14_main_stroke.xml
  app/src/main/res/layout/dialog_bottom_sheet.xml
  app/src/main/res/layout/fragment_external_cart.xml
  app/src/main/res/layout/fragment_payment.xml
  app/src/main/res/layout/fragment_scan.xml
  app/src/main/res/layout/item_cart.xml
  app/src/main/res/layout/item_spinner_payment_method.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: :sparkles: enhancement

#35 [SWS-128] 체크리스트 삭제 및 챗봇 상품메세지 체크리스트 추가 기능 구현
  app/src/main/java/com/ite/sws/domain/chatbot/view/adpater/ChatBotRecyclerViewAdapter.kt
  app/src/main/java/com/ite/sws/domain/chatbot/view/ui/ChatBotFragment.kt
  app/src/main/java/com/ite/sws/domain/checklist/api/repository/CheckListRepository.kt
  app/src/main/java/com/ite/sws/domain/checklist/api/service/CheckListService.kt
  app/src/main/java/com/ite/sws/domain/checklist/data/PostCheckListRes.kt
  app/src/main/java/com/ite/sws/domain/checklist/view/adapter/CheckListRecyclerViewAdapter.kt
  app/src/main/java/com/ite/sws/domain/checklist/view/adapter/SwipeToDeleteCallback.kt
  app/src/main/java/com/ite/sws/domain/checklist/view/ui/CheckListFragment.kt
  app/src/main/java/com/ite/sws/domain/checklist/view/ui/CheckListViewModel.kt
  app/src/main/res/drawable/bg_checklist_trash.xml
  app/src/main/res/layout/item_chatbot_product_item.xml
  app/src/main/res/layout/item_checklist.xml
  app/src/main/res/layout/item_payment_item.xml
Labels: :sparkles: enhancement

#36 [SWS-98] 푸쉬알림 연동
  app/.gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ite/sws/common/data/api/service/FcmService.kt
  app/src/main/java/com/ite/sws/domain/cart/api/repository/CartRepository.kt
  app/src/main/java/com/ite/sws/domain/cart/api/service/CartService.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/CartLoginFragment.kt
  app/src/main/java/com/ite/sws/domain/member/api/repository/MemberRepository.kt
  app/src/main/java/com/ite/sws/domain/member/api/service/MemberService.kt
  build.gradle
Labels: :sparkles: enhancement

#38 [SWS-133] 장바구니, 일행요청 리스트 변경사항 채팅 연결
  app/build.gradle
  app/src/main/java/com/ite/sws/common/WebSocketClient.kt
  app/src/main/java/com/ite/sws/domain/chat/data/CartMessagePayload.kt
  app/src/main/java/com/ite/sws/domain/chat/view/adapter/ChatAdapter.kt
  app/src/main/java/com/ite/sws/domain/chat/view/ui/ChatFragment.kt
  app/src/main/res/layout/item_chat_cart_check_received.xml
  app/src/main/res/layout/item_chat_cart_check_sent.xml
  app/src/main/res/layout/item_chat_received.xml
  app/src/main/res/layout/item_chat_sent.xml
Labels: :sparkles: enhancement

#39 [SWS-132] 결제요청시 상품추천
  app/src/main/java/com/ite/sws/common/WebSocketClient.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ExternalCartFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ScanFragment.kt
  app/src/main/java/com/ite/sws/domain/payment/api/repository/PaymentRepository.kt
  app/src/main/java/com/ite/sws/domain/payment/api/service/PaymentService.kt
  app/src/main/java/com/ite/sws/domain/payment/data/GetRecommendRes.kt
  app/src/main/java/com/ite/sws/domain/payment/data/PaymentDoneDTO.kt
  app/src/main/java/com/ite/sws/domain/payment/data/PaymentItemDto.kt
  app/src/main/java/com/ite/sws/domain/payment/data/PostPaymentReq.kt
  app/src/main/java/com/ite/sws/domain/payment/view/ui/ExternalPaymentDoneFragment.kt
  app/src/main/java/com/ite/sws/domain/payment/view/ui/PaymentCardFragment.kt
  app/src/main/java/com/ite/sws/domain/payment/view/ui/PaymentFragment.kt
  app/src/main/java/com/ite/sws/domain/payment/view/ui/PaymentPasswordFragment.kt
  app/src/main/java/com/ite/sws/domain/payment/view/ui/PaymentQRFragment.kt
  app/src/main/java/com/ite/sws/domain/payment/view/ui/PaymentViewModel.kt
  app/src/main/java/com/ite/sws/domain/payment/view/ui/ProductRecommendBottomSheet.kt
  app/src/main/res/drawable/bg_qr_frame.xml
  app/src/main/res/drawable/bg_qr_white.xml
  app/src/main/res/drawable/img_hi_heendy.png
  app/src/main/res/drawable/img_qr.png
  app/src/main/res/drawable/img_stand_heendy.png
  app/src/main/res/layout/bottom_sheet_product_recommend.xml
  app/src/main/res/layout/dialog_bottom_sheet.xml
  app/src/main/res/layout/fragment_checklist.xml
  app/src/main/res/layout/fragment_external_payment_done.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_parking.xml
  app/src/main/res/layout/fragment_payment.xml
  app/src/main/res/layout/fragment_payment_card.xml
  app/src/main/res/layout/fragment_payment_password.xml
  app/src/main/res/layout/fragment_payment_q_r.xml
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles: enhancement

#41 [SWS-138] 공유체크리스트 UI 및 조회 API 연동
  app/src/main/java/com/ite/sws/domain/sharelist/api/repository/ShareListRepository.kt
  app/src/main/java/com/ite/sws/domain/sharelist/api/service/ShareListService.kt
  app/src/main/java/com/ite/sws/domain/sharelist/data/GetShareListRes.kt
  app/src/main/java/com/ite/sws/domain/sharelist/data/ShareListItem.kt
  app/src/main/java/com/ite/sws/domain/sharelist/view/adapter/BaseShareListAdapter.kt
  app/src/main/java/com/ite/sws/domain/sharelist/view/adapter/ShareListDiffCallback.kt
  app/src/main/java/com/ite/sws/domain/sharelist/view/adapter/ShareListRecyclerAdapter.kt
  app/src/main/java/com/ite/sws/domain/sharelist/view/ui/BaseShareListViewModel.kt
  app/src/main/java/com/ite/sws/domain/sharelist/view/ui/ShareListFragment.kt
  app/src/main/java/com/ite/sws/domain/sharelist/view/ui/ShareListViewModel.kt
  app/src/main/java/com/ite/sws/util/SwipeHelperCallbackShare.kt
  app/src/main/res/layout/fragment_external_share_list.xml
  app/src/main/res/layout/fragment_share_list.xml
  app/src/main/res/layout/item_sharelist.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles: enhancement

#40 [SWS-140] 워치 연결 및 주차 정산 조회
  app/build.gradle
  app/src/main/java/com/ite/sws/domain/member/api/repository/MemberRepository.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/LoginFragment.kt
  app/src/main/java/com/ite/sws/domain/parking/view/ui/ParkingFragment.kt
Labels: :sparkles: enhancement

#43 [SWS-139] 공유체크리스트 아이템 삭제 API 연동
  app/src/main/java/com/ite/sws/domain/sharelist/api/repository/ShareListRepository.kt
  app/src/main/java/com/ite/sws/domain/sharelist/api/service/ShareListService.kt
  app/src/main/java/com/ite/sws/domain/sharelist/data/ShareListMessageDTO.kt
  app/src/main/java/com/ite/sws/domain/sharelist/view/adapter/BaseShareListAdapter.kt
  app/src/main/java/com/ite/sws/domain/sharelist/view/ui/BaseShareListViewModel.kt
  app/src/main/java/com/ite/sws/domain/sharelist/view/ui/ShareListFragment.kt
  app/src/main/java/com/ite/sws/domain/sharelist/view/ui/ShareListViewModel.kt
Labels: :sparkles: enhancement

#42 [SWS-146] 장바구니 (본인)채팅 레이아웃 수정
  app/src/main/java/com/ite/sws/domain/chat/view/adapter/ChatAdapter.kt
  app/src/main/res/layout/item_chat_cart_check_received.xml
  app/src/main/res/layout/item_chat_cart_check_sent.xml
Labels: :sparkles: enhancement

#45 [SWS-150] 결제 비밀번호 적용
  app/src/main/java/com/ite/sws/domain/payment/view/ui/PaymentPasswordFragment.kt
  app/src/main/res/drawable/ic_back_space.xml
  app/src/main/res/drawable/ic_payment_key_pad.xml
  app/src/main/res/drawable/ic_payment_password.xml
  app/src/main/res/layout/fragment_payment_password.xml
Labels: :sparkles: enhancement

#47 [SWS-152] 리뷰 상세 조회, 삭제 추가
  app/src/main/java/com/ite/sws/common/util/VideoUtil.kt
  app/src/main/java/com/ite/sws/domain/product/api/repository/ProductRepository.kt
  app/src/main/java/com/ite/sws/domain/product/api/service/ProductService.kt
  app/src/main/java/com/ite/sws/domain/product/data/GetProductReviewRes.kt
  app/src/main/java/com/ite/sws/domain/product/view/adatper/ProductImageAdatper.kt
  app/src/main/java/com/ite/sws/domain/product/view/ui/ProductFragment.kt
  app/src/main/java/com/ite/sws/domain/review/api/repository/ReviewRepository.kt
  app/src/main/java/com/ite/sws/domain/review/api/service/ReviewService.kt
  app/src/main/java/com/ite/sws/domain/review/view/adapter/ReviewAdapter.kt
  app/src/main/java/com/ite/sws/domain/review/view/ui/BaseVideoFragment.kt
  app/src/main/java/com/ite/sws/domain/review/view/ui/ReviewDetailFragment.java
  app/src/main/java/com/ite/sws/domain/review/view/ui/ReviewDetailFragment.kt
  app/src/main/java/com/ite/sws/domain/review/view/ui/ReviewFragment.kt
  app/src/main/java/com/ite/sws/domain/review/view/ui/ReviewUploadFragment.kt
  app/src/main/res/drawable/bg_product_info.xml
  app/src/main/res/layout/fragment_product_detail.xml
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/layout/item_product_review_image.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles: enhancement

#48 [SWS-149] 리프레시 토큰을 이용한 액세스 토큰 재발급
  app/src/main/java/com/ite/sws/common/RetrofitClient.kt
  app/src/main/java/com/ite/sws/domain/member/api/repository/MemberRepository.kt
  app/src/main/java/com/ite/sws/domain/member/api/service/MemberService.kt
  app/src/main/java/com/ite/sws/domain/member/data/PostLoginRes.kt
  app/src/main/java/com/ite/sws/util/SharedPreferencesUtil.kt
Labels: :sparkles: enhancement

#50 [SWS-154] 리뷰 작성 목록 - 리뷰 삭제 및 리뷰 상세 조회 기능 추가
  app/src/main/java/com/ite/sws/domain/member/view/adapter/MyReviewRecyclerViewAdapter.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/MemberViewModel.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/MyReviewFragment.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/WrittenReviewFragment.kt
Labels: :sparkles: enhancement

#51 [SWS-151] 일행요청리스트 생성
  app/src/main/java/com/ite/sws/domain/sharelist/view/adapter/ProductSearchAdapter.kt
  app/src/main/java/com/ite/sws/domain/sharelist/view/ui/ExternalShareListFragment.kt
  app/src/main/java/com/ite/sws/domain/sharelist/view/ui/ExternalShareListViewModel.kt
  app/src/main/res/drawable/bg_search_bar.png
  app/src/main/res/drawable/img_qr.png
  app/src/main/res/layout/fragment_external_share_list.xml
  app/src/main/res/layout/item_product.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles: enhancement

#52 [SWS-157] 로그인 화면 디자인 통일
  app/src/main/java/com/ite/sws/SplashActivity.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/CartLoginFragment.kt
  app/src/main/res/layout/fragment_cart_login.xml
Labels: :recycle: refactor

#55 [SWS-159] 회원가입 유효성 검사 에러 처리
  app/src/main/java/com/ite/sws/domain/member/api/repository/MemberRepository.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/SignUpFragment.kt
  app/src/main/res/layout/fragment_modify_member.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/values/colors.xml
Labels: :sparkles: enhancement, :recycle: refactor

#56 [SWS-162] 체크리스트 리팩토링
  app/src/main/java/com/ite/sws/domain/checklist/api/service/CheckListService.kt
  app/src/main/java/com/ite/sws/domain/checklist/view/adapter/CheckListRecyclerViewAdapter.kt
  app/src/main/java/com/ite/sws/domain/checklist/view/ui/CheckListFragment.kt
  app/src/main/java/com/ite/sws/domain/checklist/view/ui/CheckListViewModel.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/ExampleFragment.kt
  app/src/main/java/com/ite/sws/domain/member/view/ui/WrittenReviewFragment.kt
  app/src/main/res/layout/dialog_checklist.xml
  app/src/main/res/layout/fragment_checklist.xml
  app/src/main/res/layout/fragment_example.xml
  app/src/main/res/layout/fragment_my_review.xml
  app/src/main/res/layout/fragment_my_review_list.xml
  app/src/main/res/layout/fragment_my_review_written.xml
  app/src/main/res/layout/item_payment.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles: enhancement, :recycle: refactor

#58 [SWS-163] 주차 정산 API 연동
  app/src/main/java/com/ite/sws/domain/chat/view/adapter/ChatAdapter.kt
  app/src/main/java/com/ite/sws/domain/parking/api/repository/ParkingRepository.kt
  app/src/main/java/com/ite/sws/domain/parking/api/service/ParkingService.kt
  app/src/main/java/com/ite/sws/domain/parking/data/GetParkingRes.kt
  app/src/main/java/com/ite/sws/domain/parking/view/ui/ParkingFragment.kt
  app/src/main/java/com/ite/sws/domain/payment/data/PostParkingPaymentsReq.kt
  app/src/main/java/com/ite/sws/domain/payment/view/ui/ParkingPaymentFragment.kt
  app/src/main/java/com/ite/sws/domain/payment/view/ui/PaymentPasswordFragment.kt
  app/src/main/res/layout/fragment_parking.xml
  app/src/main/res/layout/fragment_parking_payment.xml
  app/src/main/res/layout/item_chat_received.xml
  app/src/main/res/layout/item_chat_sent.xml
Labels: :sparkles: enhancement

#57 [SWS-164] 리뷰 및 상품 상세보기 디자인 보완
  app/src/main/java/com/ite/sws/domain/product/view/ui/ProductFragment.kt
  app/src/main/java/com/ite/sws/domain/review/view/ui/ReviewUploadFragment.kt
  app/src/main/res/drawable/bg_nav.xml
  app/src/main/res/layout/fragment_my_review_upload.xml
  app/src/main/res/layout/fragment_product_detail.xml
Labels: :sparkles: enhancement, :recycle: refactor

#59 [SWS-166] 젤뽀 챗봇 상품 메세지 화면 변경
  app/src/main/java/com/ite/sws/domain/chatbot/view/adpater/ChatBotProductRecyclerViewAdapter.kt
  app/src/main/java/com/ite/sws/domain/chatbot/view/adpater/ChatBotRecyclerViewAdapter.kt
  app/src/main/res/layout/item_chatbot_product.xml
  app/src/main/res/layout/item_chatbot_product_item.xml
Labels: :sparkles: enhancement, :recycle: refactor

#60 [SWS-158] 비회원 로그인 정보있을 시, 자동로그인
  app/src/main/java/com/ite/sws/MainActivity.kt
  app/src/main/java/com/ite/sws/domain/cart/api/repository/CartRepository.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ContainerFragment.kt
  app/src/main/res/drawable/ic_red_dot.xml
  app/src/main/res/layout/fragment_container.xml
  app/src/main/res/layout/fragment_external_cart.xml
  app/src/main/res/layout/fragment_external_container.xml
  app/src/main/res/layout/fragment_external_share_list.xml
  app/src/main/res/layout/fragment_share_list.xml
Labels: :sparkles: enhancement

#61 [SWS-167] 스캔앤고 프래그먼트를 첫 시작으로 지정했을 시, 웹소켓 에러 발생 문제 해결
  app/src/main/java/com/ite/sws/MainActivity.kt
  app/src/main/java/com/ite/sws/common/WebSocketClient.kt
  app/src/main/java/com/ite/sws/domain/cart/api/repository/CartRepository.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ContainerFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ExternalContainerFragment.kt
  app/src/main/java/com/ite/sws/domain/cart/view/ui/ScanFragment.kt
  app/src/main/java/com/ite/sws/domain/payment/view/ui/ExteranlPaymentFragment.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: :bug: bug
